### ISSUE TITLE
Modal not translated

### ISSUE THREAD

**Issue by NormanHuth** [gobrightspot/nova-detached-actions#23]
The modal popup is not translated.

![Unbenannt](https://user-images.githubusercontent.com/26193232/93172397-15d29c80-f72b-11ea-9fcb-2bbb331ded65.PNG)

**Comment by eoghanobrien** [comment]
We just use Nova's modal component, can you confirm that a Nova action will translate that area first?

Which version of Nova are you using?

**Comment by oleghmelevschi** [comment]
Hi! 

Same here:

![image](https://user-images.githubusercontent.com/4750418/93548335-02931d00-f935-11ea-8a26-8a32f79204d5.png)

The code:
![image](https://user-images.githubusercontent.com/4750418/93548538-6584b400-f935-11ea-951d-8144abfb939e.png)

Also have the label() method in the Action filled with the right translation.

**Comment by eoghanobrien** [comment]
Thanks! I've confirmed where this is happening. Expect a release soon to fix this.

**Comment by eoghanobrien** [comment]
Actually, you should be able to update this yourself using the `name()` method.

```php
    public function name()
    {
        return __('Import User');
    }
```

or via `withMeta()`:

```php
    return [
        (new ClearCache('brands')->withMeta([
            'name' => __('Clear cache')
        ]);
    ]
```
