### ISSUE TITLE
Error of detach action on display view of resource not index view.

### ISSUE THREAD

**Issue by kriskristoffersonnabua** [gobrightspot/nova-detached-actions#24]
![image](https://user-images.githubusercontent.com/23304867/93187212-25c19f00-f772-11ea-9f73-c8e4b591b3b9.png)

**Comment by eoghanobrien** [comment]
There's not enough information provided to do anything with this from my end.

One thing to note is, Nova does not allow multiple packages to extend the same component, so if you already have a third-party package using the same component we're using to add our detached actions behavior, you'll get a conflict.

See https://github.com/gobrightspot/nova-detached-actions/issues/9 and https://github.com/gobrightspot/nova-detached-actions/pull/12

**Comment by kriskristoffersonnabua** [comment]
I am not actually using any other package that would conflict with actions of nova. the action runs on the index view but within the detail view of the resource the button/action when I click it that error on the console above pops up and the action logic does not run. not sure about this.

**Comment by eoghanobrien** [comment]
Which version of our package are you using and which version of Nova?

**Comment by kriskristoffersonnabua** [comment]
"laravel/nova": "~3.0",

for this repo, i used the latest version when i composer installed the package, i don't have the version because i reverted the changes because of the error.

**Comment by eoghanobrien** [comment]
It looks like standalone actions will be added soon, so unless we get a large outcry of support to keep this alive, we'll probably be deprecating this package soon: [Standalone Actions #961](https://github.com/laravel/nova/pull/961)

**Comment by dmason30** [comment]
@eoghanobrien Considering Standalone actions were just released. I agree that the main purpose of this package is now provided out of the box with nova. However, I would still prefer to have a 'detached' button rather than dropdown for certain actions when on index view. 

Would you be willing to change the `DetachedAction` to set the action as standalone by default and then also continue placing it 'detached' from the actions dropdown if possible?

**Comment by eoghanobrien** [comment]
@dmason30 I'll consider it, I don't have a lot of time right now though I would probably accept a PR, if you want to give it blast.

**Comment by eoghanobrien** [comment]
@kriskristoffersonnabua I've just tagged a new release v1.0.9

**Comment by kriskristoffersonnabua** [comment]
Thanks will try this new release.
