### ISSUE TITLE
Update resource table after action executed

### ISSUE THREAD

**Issue by rulyaryu** [gobrightspot/nova-detached-actions#26]
Hi! I use this package for a quick resource creating but after the action was executed resource table doesn't update its state.
I think it's because there is no event emitted (in nova original action it named as "actionExecuted").
Maybe you can add some additional configurable property to manage this kinda situation?

**Comment by eoghanobrien** [comment]
I've figured this out and will release a new version with this feature soon.

**Comment by eoghanobrien** [comment]
Fixed in PR #29

**Comment by rulyaryu** [comment]
Thanks!)
