### ISSUE TITLE
Handle method not executing

### ISSUE THREAD

**Issue by antoniovazevedo** [gobrightspot/nova-detached-actions#3]
Thank you for a great package.
However, I am having trouble using it, the `handle` method in my action is not being executed.

It appears the reason is that `DetachedAction` class is using  `Laravel\Nova\Actions\DispatchAction` instead of the local DispatchAction.

**Comment by vesper8** [comment]
This is still happening.. I guess it's because you haven't tagged a new release @gobrightspot ?
