### ISSUE TITLE
Chunking and performing the 'handle()' multiple times

### ISSUE THREAD

**Issue by remkobrenters** [gobrightspot/nova-detached-actions#33]
When implementing this on a fairly large set of records I noticed the `handle()` in the action was triggered multiple times (as in my total set of records divided by 200) which drew my (read my smarter colleague's) attention to the `handleRequest()` in the default Nova action.

This function was chunking up data to dispatch individual events for each chunk. In our case we just wanted to start one dispatched job which would perform it's tasks in the background. 

We resolved this for now by overruling this function with basically nothing:

    public function handleRequest(ActionRequest $request)
    {
         dispatch(new GenerateTicketReport($request->resolveFields()->toArray()));
    }

Maybe this something worth mentioning in the documentation as I can imagine more people run into this situation (probably sometimes not even knowing their action is running multiple times without being noticed).

**Comment by eoghanobrien** [comment]
@remkobrenters Thanks for creating an issue to bright this to people's attention. I'm not convinced it's within the remit of the package to handle the issue but feel free to submit a pull request with changes to the README.md explaining the issue and how to fix it.

**Comment by remkobrenters** [comment]
I created a PR to add something about this to the readme.

**Comment by eaguad1337** [comment]
@remkobrenters I'm facing the same issue but I need to check for some fields before dispatching the job. Did you manage to make it work?

**Comment by remkobrenters** [comment]
Must say I do not have direct insight in which project it was at that time but would assume you could add some logic before the dispatch() right?

**Comment by gobrightspot** [comment]
Closing this as the commit from @remkobrenters was merged.
