### ISSUE TITLE
Enhancement: default handleRequest method

### ISSUE THREAD

**Issue by Lai0n** [gobrightspot/nova-detached-actions#34]
Hi, I'm building tool to create resources with fake data and I've came across one error due to no actual database rows for that resource when executing action (nova checks that by default). And I noticed that this package already has overridden `DispatchAction::forModels()` (and removed check there) but it's not actually overriding `handleRequest` method on `DetachedAction` which is also doing that check and causing the error message "Sorry! You are not authorized to perform this action.".

My proposition is to create trait for overriding `handleRequest` (for backwards compatibility with default nova action behaviour)

**Comment by eoghanobrien** [comment]
Thanks @Lai0n Can you submit a PR with the changes you've outlined above so I can review.

**Comment by Lai0n** [comment]
Done some digging around. Turns out it was half way implemented. As I mentioned there was overridden `DispatchAction::class` but there was also forgotten member variable `DetachedAction::standalone` So instead of creating trait I just implemented it right into `DetachedAction::handleRequest`.

**Comment by Lai0n** [comment]
Find out that it was not package issue but it was Nova's. Standalone actions are not implemented until version 3.10.0, I was using older version. Please change minimum required laravel/nova package version in composer.json
