### ISSUE TITLE
action button bug

### ISSUE THREAD

**Issue by anguslui91** [gobrightspot/nova-detached-actions#60]
When I click the buttons in the index view, the sorting of the action button is changed.

**Beginning**
![image](https://user-images.githubusercontent.com/46552605/144958094-2ad18e3f-76c7-40e0-b28d-672afeef3416.png)

**Clicked**
![image](https://user-images.githubusercontent.com/46552605/144958146-061cec25-7318-46cf-88e5-a8644ba1f4ca.png)

**After run action**
![image](https://user-images.githubusercontent.com/46552605/144958186-b7ccae41-004f-434e-931a-051787b3cd87.png)

**Comment by charanguru** [comment]
I noticed this issue as well. I was able to "fix" it through sum custom css. Each detached action should come with a `dusk` attribute. In my case these were my buttons

**Comment by charanguru** [comment]
Disregard the CSS part above it doesn't work very well for different sized screens because of the `position: absolute`

I use this instead to set the order of buttons within a flex div 

```
button[dusk="run-action-button-configuration-publish"] {
    order: 1 !important;
}

button[dusk="run-action-button-configuration-edit"] {
    order: 2 !important;
}
```

**Comment by anguslui91** [comment]
> Disregard the CSS part above it doesn't work very well for different sized screens because of the `position: absolute`
> 
> I use this instead to set the order of buttons within a flex div
> 
> ```
> button[dusk="run-action-button-configuration-publish"] {
>     order: 1 !important;
> }
> 
> button[dusk="run-action-button-configuration-edit"] {
>     order: 2 !important;
> }
> ```

It's worked! Thanks a lot.
