### ISSUE TITLE
Instructions for updating to Nova 4

### ISSUE THREAD

**Issue by HeadStudios** [gobrightspot/nova-detached-actions#81]
Please provide instructions for updating this package to include Nova 4 support after the step of running composer require gobrightspot/nova-detached-actions as per your instructions in Readme.md to incorporate the updates in https://github.com/lucidlogic/nova-detached-actions

Thank you!

**Comment by eullercdr** [comment]
@HeadStudios How i install this package in Laravel Nova? Not working for me! Thanks a lot.

**Comment by eullercdr** [comment]
@gobrightspot Is There plans to fix errors in Laravel Nova?

**Comment by HeadStudios** [comment]
> @HeadStudios How i install this package in Laravel Nova? Not working for me! Thanks a lot.

Likewise here - awaiting on support or input from developer - in the meantime I am just putting this in too much time invested vs potential impact basket.

**Comment by scramatte** [comment]
+1 Same issue here

**Comment by HeadStudios** [comment]
> +1 Same issue here

I guess we just have to accept we'll have to click on drop downs lol - not a huge deal.

**Comment by alex-eftimie** [comment]
Until @gobrightspot pushes another release you can manually add the repo
```json
  "require": {
   ...
    "gobrightspot/nova-detached-actions": "dev-master#9710b19cb9b1e5759483e01bf1d57f5cb2060459"
  },
  "repositories": {
    ...
    "nda": {
      "type": "vcs",
      "url": "https://github.com/gobrightspot/nova-detached-actions.git"
    }
  }
```

**Comment by HeadStudios** [comment]
> 

Thank you! I will try this - I will report back with my results.

**Comment by HeadStudios** [comment]
> Until @gobrightspot pushes another release you can manually add the repo
> 
> ```json
>   "require": {
>    ...
>     "gobrightspot/nova-detached-actions": "dev-master#9710b19cb9b1e5759483e01bf1d57f5cb2060459"
>   },
>   "repositories": {
>     ...
>     "nda": {
>       "type": "vcs",
>       "url": "https://github.com/gobrightspot/nova-detached-actions.git"
>     }
>   }
> ```
> 
> And then update `$ composer update`

This has not worked for me. 

Below I am including Gist of my composer.json code:
https://gist.github.com/HeadStudios/5ea94eaeb816c20e5310f0b05dc0e670

Below I am including my Nova action code:
https://gist.github.com/HeadStudios/1860a51569b5c137c4a8ed3308c465fd

Below I am including my Nova resource that I am attaching action to:
https://gist.github.com/HeadStudios/3f13450ec22b01865aa6e83da5a89a15

I can also confirm I have ran composer update.

When loading resource button is not showing for me:
https://share.getcloudapp.com/QwujZlBk

I can also confirm the action does not show in any of the options on the drop down when a record checkbox is selected.

Any other input or advice would be much appreciated!

**Comment by HeadStudios** [comment]
Please ignore my previous point - I have now fixed the issue by what I suspect is taking out one of the arguments from the handle() method and adding the label method. One thing to note is it has changed some of the styling on my Contacts page by giving top and bottom borders a white color - but one thing at a time. I am closing this issue as my fundamental challenge has been resolved.
